[package]
name = "ecdsa_k_account_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.76.1", directory = "noir-projects/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.76.1", directory = "noir-projects/aztec-nr/authwit" }
ecdsa_public_key_note = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.76.1', directory = 'noir-projects/noir-contracts/contracts/ecdsa_public_key_note' }
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
